//Array que contiene objetos para simular la base de datos
const db_productos = [
  {id: 1, nombre: "Pantalón", precio: 39990, categoria: "Pantalones", descripcion: "Pantalón de mezclilla resistente y moderno.", imagen:"./assets/img/img-products/pantalones.jpg", inicial: 100, stock: 38, vendido: false, cntVendido: 62, sale: true, desc:25, cantAgg: 0},
  {id: 2, nombre: "Sudadera", precio: 29990, categoria: "Ropa deportiva", descripcion: "Sudadera ideal para actividades deportivas.", imagen:"./assets/img/img-products/sudadera.jpg", inicial: 100, stock: 53, vendido: false, cntVendido: 47, sale: false, desc:0, cantAgg: 0},
  {id: 3, nombre: "Camiseta", precio: 20990, categoria: "Ropa casual", descripcion: "Camiseta de algodón suave y cómoda.", imagen:"./assets/img/img-products/camiseta.jpg", inicial: 100, stock: 88, vendido: false, cntVendido: 12, sale: true, desc:25, cantAgg: 0},
  {id: 4, nombre: "Chaqueta", precio: 59990, categoria: "Abrigos", descripcion: "Chaqueta elegante y abrigada para el invierno.", imagen:"./assets/img/img-products/chaqueta.jpg", inicial: 100, stock: 27, vendido: false, cntVendido: 73, sale: true, desc:30, cantAgg: 0},
  {id: 5, nombre: "Vestido", precio: 49990, categoria: "Vestidos", descripcion: "Vestido femenino y moderno para ocasiones especiales.", imagen:"./assets/img/img-products/vestido.jpg", inicial: 100, stock: 40, vendido: false, cntVendido: 60, sale: false, desc:0, cantAgg: 0},
  {id: 6, nombre: "Zapatos", precio: 34990, categoria: "Calzado", descripcion: "Zapatos cómodos y elegantes para cualquier ocasión.", imagen:"./assets/img/img-products/zapatos.jpg", inicial: 100, stock: 36, vendido: false, cntVendido: 64, sale: true, desc:15, cantAgg: 0},
  {id: 7, nombre: "Gorra", precio: 15990, categoria: "Accesorios", descripcion: "Gorra casual para un estilo urbano.", imagen:"./assets/img/img-products/gorra.jpg", inicial: 100, stock: 92, vendido: false, cntVendido: 8, sale: true, desc:25, cantAgg: 0},
  {id: 8, nombre: "Calcetines", precio: 9990, categoria: "Ropa interior", descripcion: "Calcetines suaves y transpirables.", imagen:"./assets/img/img-products/calcetines.jpg", inicial: 100, stock: 23, vendido: false, cntVendido: 77, sale: false, desc:0, cantAgg: 0},
  {id: 9, nombre: "Shorts", precio: 24990, categoria: "Ropa casual", descripcion: "Shorts ligeros y perfectos para el verano.", imagen:"./assets/img/img-products/short.jpg", inicial: 100, stock: 95, vendido: false, cntVendido: 5, sale: true, desc:15, cantAgg: 0},
  {id: 10, nombre: "Blusa", precio: 27990, categoria: "Ropa casual", descripcion: "Blusa elegante y versátil para cualquier ocasión.", imagen:"./assets/img/img-products/blusa.jpg", inicial: 100, stock: 71, vendido: false, cntVendido: 29, sale: false, desc:0, cantAgg: 0},
  {id: 11, nombre: "Pijama", precio: 32990, categoria: "Ropa de dormir", descripcion: "Pijama cómodo y suave para una buena noche de sueño.", imagen:"./assets/img/img-products/pijama.jpg", inicial: 100, stock: 82, vendido: false, cntVendido: 18, sale: false, desc:0, cantAgg: 0},
  {id: 12, nombre: "Falda", precio: 22990, categoria: "Faldas", descripcion: "Falda femenina y moderna para diversas ocasiones.", imagen:"./assets/img/img-products/falda.jpg", inicial: 100, stock: 74, vendido: false, cntVendido: 26, sale: true, desc:25, cantAgg: 0},
  {id: 13, nombre: "Bufanda", precio: 18990, categoria: "Accesorios", descripcion: "Bufanda abrigada y con estilo para el invierno.", imagen:"./assets/img/img-products/bufanda.jpg", inicial: 100, stock: 54, vendido: false, cntVendido: 46, sale: false, desc:0, cantAgg: 0},
  {id: 14, nombre: "Traje de baño", precio: 39990, categoria: "Trajes de baño", descripcion: "Traje de baño moderno y cómodo para la playa.", imagen:"./assets/img/img-products/traje-de-baño.jpg", inicial: 100, stock: 7, vendido: false, cntVendido: 93, sale: false, desc:0, cantAgg: 0},
  {id: 15, nombre: "Jersey", precio: 44990, categoria: "Ropa deportiva", descripcion: "Jersey ideal para actividades deportivas en climas fríos.", imagen:"./assets/img/img-products/jersey.jpg", inicial: 100, stock: 91, vendido: false, cntVendido: 9, sale: false, desc:0, cantAgg: 0},
  {id: 16, nombre: "Sombrero", precio: 25990, categoria: "Accesorios", descripcion: "Sombrero de ala ancha para protegerse del sol con estilo.", imagen:"./assets/img/img-products/sombrero.jpg", inicial: 100, stock: 26, vendido: false, cntVendido: 74, sale: true, desc:12, cantAgg: 0},
  {id: 17, nombre: "Chaleco", precio: 33990, categoria: "Ropa casual", descripcion: "Chaleco moderno y versátil para cualquier temporada.", imagen:"./assets/img/img-products/chaleco.jpg", inicial: 100, stock: 88, vendido: false, cntVendido: 12, sale: true, desc:50, cantAgg: 0},
  {id: 18, nombre: "Pullover", precio: 28990, categoria: "Ropa deportiva", descripcion: "Pullover cómodo y transpirable para actividades deportivas.", imagen:"./assets/img/img-products/pullover.jpg", inicial: 100, stock: 96, vendido: false, cntVendido: 4, sale: true, desc:15, cantAgg: 0},
  {id: 19, nombre: "Gafas de sol", precio: 10990, categoria: "Accesorios", descripcion: "Gafas de sol con estilo para proteger los ojos del sol.", imagen:"./assets/img/img-products/lentes-sol.jpg", inicial: 100, stock: 37, vendido: false, cntVendido: 63, sale: false, desc:0, cantAgg: 0},
  {id: 20, nombre: "Reloj", precio: 12990, categoria: "Accesorios", descripcion: "Reloj elegante para complementar tu atuendo.", imagen:"./assets/img/img-products/reloj.jpg", inicial: 100, stock: 63, vendido: false, cntVendido: 37, sale: false, desc: 0, cantAgg: 0}
];

export default db_productos;